# Generated by Django 4.1.6 on 2023-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingsettings',
            name='from_zero',
            field=models.BooleanField(default=False, help_text='Rating starts from 0 or 1'),
        ),
    ]
